import { Lead, User } from '../../types/index.ts';

export const leadStatusOptions = ['NEW', 'CONTACTED', 'QUALIFIED', 'PROPOSAL', 'NEGOTIATION', 'CONVERTED', 'LOST', 'FOLLOW_UP'];
export const leadPriorityOptions = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];
export const leadSourceOptions = ['Website', 'LinkedIn', 'Conference', 'Referral', 'Outbound', 'Partner'];
export const followUpTypes = ['Call', 'Email', 'Meeting', 'WhatsApp', 'Other'];

export const INITIAL_USERS: User[] = [
  { id: 'usr_1', name: 'Sarah Jenkins', email: 'sarah@acme.io', role: 'ADMIN', organizationId: 'org_acme', createdAt: new Date() },
  { id: 'usr_2', name: 'Marcus Wright', email: 'marcus@acme.io', role: 'SALES', organizationId: 'org_acme', createdAt: new Date() },
  { id: 'usr_3', name: 'Elena Rostova', email: 'elena@acme.io', role: 'SALES', organizationId: 'org_acme', createdAt: new Date() },
  { id: 'usr_4', name: 'Devon Vance', email: 'devon@acme.io', role: 'SUPPORT', organizationId: 'org_acme', createdAt: new Date() },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead_1',
    name: 'Alex Morgan',
    firstName: 'Alex',
    lastName: 'Morgan',
    company: 'FintechCorp',
    email: 'alex.morgan@fintechcorp.com',
    phone: '+1 555-234-8901',
    alternatePhone: '+1 555-234-8902',
    source: 'LinkedIn',
    industry: 'Financial Services',
    jobTitle: 'VP of Finance',
    companySize: '201-500',
    score: 85,
    status: 'QUALIFIED',
    priority: 'HIGH',
    assignedToId: 'usr_2',
    assignedTeam: 'Enterprise Sales',
    assignedDealer: 'NorthPeak Distribution',
    nextFollowUp: new Date(Date.now() + 86400000 * 2),
    followUpType: 'Meeting',
    notes: 'Interested in enterprise seat licensing and budget approved for Q4 deployment.',
    organizationId: 'org_acme',
    createdAt: new Date(Date.now() - 86400000 * 3),
    updatedAt: new Date(),
  },
  {
    id: 'lead_2',
    name: 'Samantha Vance',
    firstName: 'Samantha',
    lastName: 'Vance',
    company: 'Aerodynamics.io',
    email: 'svance@aerodynamics.io',
    phone: '+1 555-891-2304',
    source: 'Website',
    industry: 'Aerospace',
    jobTitle: 'Operations Director',
    companySize: '51-200',
    score: 62,
    status: 'NEW',
    priority: 'MEDIUM',
    assignedToId: 'usr_3',
    assignedTeam: 'SMB Growth',
    nextFollowUp: new Date(Date.now() + 86400000),
    followUpType: 'Call',
    notes: 'Requested a demo for workflow automation and operational cost savings.',
    organizationId: 'org_acme',
    createdAt: new Date(Date.now() - 86400000 * 5),
    updatedAt: new Date(),
  },
  {
    id: 'lead_3',
    name: 'Liam Chen',
    firstName: 'Liam',
    lastName: 'Chen',
    company: 'BioLabs Tech',
    email: 'lchen@biolabs.tech',
    phone: '+1 555-432-1920',
    source: 'Conference',
    industry: 'Healthcare',
    jobTitle: 'Head of Digital Health',
    companySize: '201-500',
    score: 92,
    status: 'NEGOTIATION',
    priority: 'URGENT',
    assignedToId: 'usr_2',
    assignedTeam: 'Enterprise Sales',
    assignedDealer: 'SummitWorks',
    nextFollowUp: new Date(Date.now() + 86400000 * 3),
    followUpType: 'Meeting',
    notes: 'Clinical deployment interest; procurement team is reviewing annual licensing terms.',
    organizationId: 'org_acme',
    createdAt: new Date(Date.now() - 86400000 * 7),
    updatedAt: new Date(),
  },
  {
    id: 'lead_4',
    name: 'Chloe Dubois',
    firstName: 'Chloe',
    lastName: 'Dubois',
    company: 'ParisConsult Europe',
    email: 'cdubois@parisconsult.eu',
    phone: '+33 1 42 68 55 00',
    source: 'Referral',
    industry: 'Professional Services',
    jobTitle: 'Partner Manager',
    companySize: '11-50',
    score: 74,
    status: 'PROPOSAL',
    priority: 'HIGH',
    assignedToId: 'usr_1',
    assignedTeam: 'Channel Sales',
    assignedDealer: 'Silverline Retail',
    nextFollowUp: new Date(Date.now() + 86400000 * 4),
    followUpType: 'Email',
    notes: 'Referral from existing customer; needs pricing on multi-region expansion rollout.',
    organizationId: 'org_acme',
    createdAt: new Date(Date.now() - 86400000 * 10),
    updatedAt: new Date(),
  },
  {
    id: 'lead_5',
    name: 'David Miller',
    firstName: 'David',
    lastName: 'Miller',
    company: 'Constructo',
    email: 'david@constructo.com',
    phone: '+1 555-321-7788',
    source: 'Outbound',
    industry: 'Construction',
    jobTitle: 'Procurement Lead',
    companySize: '500-1000',
    score: 35,
    status: 'LOST',
    priority: 'LOW',
    assignedToId: 'usr_3',
    assignedTeam: 'Field Sales',
    nextFollowUp: new Date(Date.now() - 86400000 * 2),
    followUpType: 'Call',
    notes: 'Lead went quiet after procurement freeze. Follow-up may reopen next quarter.',
    organizationId: 'org_acme',
    createdAt: new Date(Date.now() - 86400000 * 18),
    updatedAt: new Date(),
  },
  {
    id: 'lead_6',
    name: 'Priya Shah',
    firstName: 'Priya',
    lastName: 'Shah',
    company: 'Cloud Matrix',
    email: 'priya@cloudmatrix.ai',
    phone: '+1 415-448-1200',
    source: 'Partner',
    industry: 'Software',
    jobTitle: 'VP Sales',
    companySize: '201-500',
    score: 78,
    status: 'CONTACTED',
    priority: 'HIGH',
    assignedToId: 'usr_4',
    assignedTeam: 'Partnerships',
    assignedDealer: 'Harbor Trade Group',
    nextFollowUp: new Date(Date.now() + 86400000 * 1.5),
    followUpType: 'WhatsApp',
    notes: 'Strong interest in automation suite and onboarding support package.',
    organizationId: 'org_acme',
    createdAt: new Date(Date.now() - 86400000 * 6),
    updatedAt: new Date(),
  },
];
